[public_goods]
title = "공공재 게임 규칙"
rules = [
    "당신은 게임이 시작될 때 100 포인트를 받습니다.",
    "각 라운드마다, 당신은 잔고의 절반 이하의 임의의 금액을 공동 계좌에 기부할 수 있습니다 (한푼도 기부하지 않을 수도 있습니다).",
    "라운드가 끝나면 공동 계좌에 모인 총액에 1.5배가 곱해지고, 모든 참가자에게 똑같이 분배됩니다.",
    "분배된 포인트에서 처음에 기부한 포인트를 뺸만큼 잔고가 증가합니다.",
    "당신의 목표는 개인의 이익과 집단의 이익 사이에서 최적의 결정을 내리는 것입니다.",
    "모두 10번의 라운드를 진행합니다."
]

example = [
    "당신이 20 포인트를 공공 투자에 기부합니다.",
    "상대 에이전트들이 각각 10, 15, 5, 30 포인트를 기부하여, 총 기부액은 20 + 10 + 15 + 5 + 30 = **80 포인트**가 됩니다.",
    "이 금액은 1.5배로 늘어나 총액은 **80 × 1.5 = 120 포인트**가 됩니다.",
    "총액을 5명이 나눠 가지므로, 당신은 **120 ÷ 5 = 24 포인트**를 돌려받습니다.",
    "당신의 잔고는 처음 100 포인트에서 20 포인트를 차감한 후, 24 포인트를 돌려받아 **104 포인트**가 됩니다."
]
next_page_text = "공공재 게임 시작하기"
next_page_url = "/app/public-goods"


[section1]
title = "신뢰 게임 규칙 (수신자 역할)"
rules = [
    "당신은 수신자 역할을 맡게 됩니다.",
    "각 라운드마다 송금자가 일정한 포인트를 당신에게 투자합니다.",
    "당신은 송금자가 보낸 금액의 3배를 받습니다.",
    "이중 원하는 만큼 송금자에게 돌려줄 수 있습니다.",
    "얼마를 반환할 지 현명하게 결정하십시오.",
    "모두 10번의 라운드를 진행합니다."
]
next_page_text = "신뢰 게임 (수신자) 시작하기"
next_page_url = "/app/section1"


[section2]
title = "신뢰 게임 규칙 (수탁자 역할)"
rules = [
    "당신은 수탁자 역할을 맡아 포인트를 투자하게 됩니다.",
    "서로 다른 신뢰도를 지닌 4명의 상대와 차례로 게임을 진행합니다.",
    "각 게임은 모두 10번의 라운드로 구성됩니다.",
    "각 라운드마다 당신은 10 포인트의 초기 자금을 받습니다.",
    "수신자에게 0에서 현재 잔고의 50% 사이의 금액을 투자할 수 있습니다.",
    "당신이 투자한 금액은 3배가 되어 수신자에게 전달됩니다.",
    "수신자는 전달받은 금액 중 일부를 당신에게 돌려줄 것입니다.",
    "상대가 바뀔 때마다 수신자의 반환 전략이 달라집니다.",
    "상대의 신뢰도를 잘 가늠하여 투자액을 현명하게 결정하십시오."
]
next_page_text = "신뢰 게임 (수탁자) 시작하기"
next_page_url = "/app/section2"


