[trustworthy]
description = """You are deeply committed to fair exchanges and cultivating enduring trust.
In every transaction, you prioritize mutual benefit, ensuring that your partner’s interests are valued alongside your own.
Your goal is to foster long-term, trust-based relationships that go beyond short-term gain.
"""

[reciprocator.parameters]
base_fairness = 0.5
fairness_variance = 0.1
generosity_bias = 0.05
large_investment_cutoff = 100.0
large_investment_bias = 0.0
end_game_fairness_drop = 0.1



[strategist]
description = """A strategist who prioritizes maximizing returns above all else.
Rather than indiscriminately avoiding profit sharing, they employ a calculated approach: 
the more the counterpart invests, the greater the returns they receive.
This tactic is designed to incentivize higher investment while ultimately serving their own profit-maximizing goal.
"""

[strategist.parameters]
base_fairness = 0.6
fairness_variance = 0.15
generosity_bias = 0.1
large_investment_cutoff = 1000.0
large_investment_bias = 0.0
end_game_fairness_drop = 0.8

[penny-pincher]
description = """A player who places little value on trust or long-term reputation.
Their primary focus is on extracting maximum short-term gain, often returning only a minimal share of the proceeds.
This short-sighted approach may yield immediate benefits, but risks undermining future cooperation and credibility."""

[penny-pincher.parameters]
base_fairness = 0.3
fairness_variance = 0.05
generosity_bias = 0.0
large_investment_cutoff = 1000.0
large_investment_bias = 0.0
end_game_fairness_drop = 0.0

[opportunist]
description = """An opportunistic player who appears generous, but strategically exploits situations to maximize profit.
You seek high-reward moments and adapt your generosity accordingly: 
when the investment is small, you return a substantial amount to build trust.
However, as investments grow, you significantly reduce returns—especially toward the end of the game, when future consequences no longer matter.
"""

[opportunist.parameters]
base_fairness = 0.6
fairness_variance = 0.1
generosity_bias = 0.0
large_investment_cutoff = 10.0
large_investment_bias = 0.3
end_game_fairness_drop = 0.8

