[UCLA]
likert_level = 4
likert_anchor = ["전혀 그렇지 않다",
"별로 그렇지 않다",
"가끔 그런 편이다",
"항상 그렇다"]
items = ["나는 주위 사람들과 ‘조화’를 이룬다고 느껴진다",
"나는 나와 같이 있어 줄 사람이 부족하다",
"나는 도움을 청할 사람이 아무도 없다",
"나는 혼자가 아니라고 느껴진다",
"나는 친구들 안에 속해 있다고 느껴진다",
"나는 주위 사람들과 공통점이 많다",
"나는 더 이상 어느 누구와도 가깝지 않다",
"내 주변에는 나의 관심사나 의견을 나눌 사람이 없다",
"나는 주위 사람에게 사교적이고 친근하게 다가간다",
"나는 주위 사람들과 가깝다고 느껴진다",
"나는 혼자 남겨진 것 같다고 느껴진다",
"나와 다른 사람들과의 관계는 깊지 않다",
"나를 누구도 진정으로 아는 사람은 없다",
"나는 사람들 사이에서 고립되어 있다고 느껴진다",
"나는 내가 원할 때는 같이 있어 줄 사람을 찾을 수 있다",
"나를 진정으로 이해해주는 사람들이 있다",
"나는 내가 내성적인 것이 불만이다",
"내 주위에 사람들은 있지만 나와 함께 할 사람은 없다",
"나는 나와 대화를 나눌 수 있는 사람이 있다",
"나는 내가 의지할 만한 사람이 있다"]
reverse_coding = [1,4,5,6,9,10,15,16,19,20]

[DASS]
likert_level = 4 
likert_anchor = ["전혀 아니다",
"약간 또는 가끔",
"상당히, 자주",
"매우 많이, 거의 대부분"]
items = ["나는 안정을 취하기 힘들었다",
    "입이 바싹 마르는 느낌이 들었다",
    "어떤 것에도 긍정적인 감정을 느낄 수가 없었다",
    "숨쉬기가 곤란한 적이 있었다",
    "무엇인가를 시작하는 것이 어려웠다",
    "어떤 상황에 과잉 반응을 보이는 경향이 있었다",
    "몸이 떨리는 것을 느꼈다(예: 손 떨림)",
    "모든 일에 신경을 너무 많이 쓴다고 느꼈다",
    "내가 너무 당황해서 웃음거리가 될까 봐 걱정했다",
    "나는 기대할 것이 아무것도 없다는 생각이 들었다",
    "자꾸 초조해졌다",
    "나는 진정하는 것이 어려웠다",
    "기운이 처지고 우울했다",
    "내가 하는 일에 방해가 되는 것을 용납할 수 없었다",
    "내 자신이 심한 불안상태까지 도달했음을 느꼈다",
    "어떤 것에도 몰두 할 수가 없었다",
    "나는 사람으로서 가치가 없다고 느꼈다",
    "내가 꽤 신경질적이라고 느꼈다",
    "가만히 있을 때에도 심장이 두근거리는 것이 느껴졌다",
    "아무 이유 없이 무서움을 느꼈다",
    "산다는 것이 의미가 없다는 생각이 들었다",
]

[TRUST]

likert_level = 5
likert_anchor = ["전혀 아니다",
"아니다",
"보통이다",
"그렇다",
"매우 그렇다"]
items = ["사람들이 내 의견을 존중한다",
    "나는 대체로 사람을 잘 믿는 편이다",
    "나는 가족들로부터 사랑받는다고 느낀다",
    "사람들이 나를 대수롭지 않게 보는 것 같다",
    "혹시 사람들에게 나쁜 인상을 줄까봐 신경을 많이 쓴다",
    "우리 가족들은 나를 믿는다",
    "나는 사람들에게 호감을 주는 것 같다",
    "사람들이 내 말에 귀를 기울이지 않는다",
    "나는 친구가 별로 없다",
    "사람들이 어떻게 볼까 많이 의식하며 행동하는 편이다",
    "사람들의 신뢰를 별로 받지 못한다",
    "누가 내게 말을 걸어오면 불안해진다",
    "어려운 상황이 되면 친구들이 나를 외면할 것이다",
    "사람들이 나를 좀 대하기 어려워하는 것 같다",
   "관계가 나빠질까봐 상대의 무리한 요구도 들어준다",
    "사람들이 나를 좋지 않게 보는 것 같다",
    "가족들과 함께 있으면 마음이 즐겁고 편하다",
    "우리 가족들은 내 심정을 잘 이해해준다"
]